### ISSUE TITLE
Cannot find module 'broccoli-static-compiler'

### ISSUE THREAD

**Issue by ritesh83** [green-arrow/ember-cli-chosen#15]
I created a new ember cli project with ember-cli version 0.2.2.
When I run 

```
ember install:addon ember-cli-chosen.
```

I get the following error:

```
Cannot find module 'broccoli-static-compiler'
Error: Cannot find module 'broccoli-static-compiler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/keswanir/work/testchosen/testbrocc/node_modules/ember-cli-  chosen/index.js:4:21)
```

If I install broccoli-static-compiler, it works fine but isn't the addon suppose to install its dependencies?

**Comment by ChrisHonniball** [comment]
I do not have ember-cli-chosen installed and I get that as well. I'm not sure which one of my npm modules is looking for it.

**Comment by mkolenda** [comment]
I get a similar error after running ember install:addon ember-cli-chosen on a mature ember-cli project that did not have this error prior to running the command:

$ ember install:addon ember-cli-chosen
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Installed packages for tooling via npm.
Cannot find module 'broccoli-static-compiler'
Error: Cannot find module 'broccoli-static-compiler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/projects/find_a_doctor/node_modules/ember-cli-chosen/index.js:4:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

My environment:
Ember      : 1.9.1
Ember Data : 1.0.0-beta.12
Handlebars : 2.0.0
jQuery     : 1.11.3
ember-cli: 0.1.5

I see here: http://www.ember-cli.com/#managing-dependencies that "Note: broccoli-static-compiler is deprecated. Use broccoli-funnel instead."
